### ISSUE TITLE
Impossible de le faire fonctionner avec authentification NGINX.

### ISSUE THREAD

**Issue by Silvers12** [xataz/gobrowser#14]
Salut,

Déja un gros merci pour ce boulot ! C'est vraimant top !

J'ai un petit souci pour le faire fonctionner avec authentification. Si je met dans les paramètres : http://monsite.net:5000 Je n'ai pas besoin de mot de passe.

Du coup je le fait tourner sur le localhost:5000.

dans mon NGINX j'utilise donc un proxy_pass pour rediriger http://monsite.net/GoBrowser vers le localhost:5000 et ca marche. 
La où ca ne marche plus c'est pour l’arborescence. Je vois bien ma liste de dossier. Mais quand je click sur "Recette" au lieu d'ouvrir le dossier mon url devient http://monsite.net/Recette. Et mon serveur ne connait pas cette adresse donc Error 404...

Voici mon nginx 
## Config GoBrowser ##
	location /gobrowser {
		rewrite ^/gobrowser /$1 break;
		proxy_pass http://127.0.0.1:5000;
        }

C'est une version parmis tant d'autre j'en ai tellement essayé ...

Si vous avez une solution ? Le but étant de ne pas exposer gobrowser a n'importe qui connaissant mon ip... 

Merci :)

**Comment by xataz** [comment]
Salut,

As tu lancé gobrowser avec l'option `-webroot` ?

Normalement tu n'as pas de règles spécifique à ajouter sur nginx

Lancement de gobrowser : 
```shell
./app -listen 127.0.0.1:5000 -path /home/xataz -forcessl -webroot /files
```

nginx : 
```
location /files {
	proxy_pass http://127.0.0.1:5000;
    }
```

**Comment by Silvers12** [comment]
Mais non !!!!!! 👍 
Je suis trop bête j'avais pas vu cette option ^^ J'ai passé une journée complète a manipuler NGINX pour rien !!! ^^ 
Merci tu es un chef !

C'est vraiment du super bon boulot !
