### ISSUE TITLE
Trier la shareslist par la colonne "name"

### ISSUE THREAD

**Issue by lokiiiii** [xataz/gobrowser#3]
Hello Xataz :)
Je veux pas te souler, je sais que t'as autre chose à faire, juste pour savoir si tu pouvais m'expliquer comment modifier la page shareslist juste pour pouvoir trier les liens par la colonne "name", car là je pense que c'est trier par nom du fichier "lien" et c'est pas très pratique quand il y en a beaucoup :)
Merci beaucoup, et si t'as pas le temps, aucun soucis !

**Comment by kidburglar** [comment]
Comme je ne suis pas sûr que la PR à trigger un message je me permets d'en faire un moi-même.

La PR trie automatiquement la colonne name, y a juste parfois une petite latence car le plugin jquery ne retiens pas le tri, mais c'est minime comme souci.

Je ne suis pas sur concernant la licence par contre, donc je laisse ça aux experts
